name: GET Cloudflare

on:
  schedule:
    # Runs daily at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  get-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Fetch Cloudflare data
        env:
          CLOUDFLARE_ZONE_TAG: ${{ secrets.CLOUDFLARE_ZONE_TAG }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        run: npm run get-cloudflare

      - name: Check for changes
        run: |
          git diff --quiet || echo "Changes detected"

      - name: Configure Git
        if: success()
        run: |
          git config --local user.name "ocf-bot"
          git config --local user.email "info@openclimatefix.org"

      - name: Commit changes
        if: success() && (run: git diff --quiet; echo $?)
        run: |
          git add .
          git commit -m "🗃 Add latest Cloudflare data"

      - name: Fetch latest changes from main
        run: git pull --rebase origin main

      - name: Push changes
        run: git push origin HEAD:main
